import dynamic from "next/dynamic";
import type { WidgetCategory, WidgetDefinition } from "@/types/dashboard";

const widgets: WidgetDefinition[] = [
  // ── StatCard widgets (top row, ~120px) ─────────────────────────────
  {
    id: "total-pnl",
    name: "Total P&L",
    description: "Total profit and loss across all trades",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/total-pnl")),
  },
  {
    id: "win-rate",
    name: "Win Rate",
    description: "Percentage of winning trades",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/win-rate")),
  },
  {
    id: "trades-today",
    name: "Trades Today",
    description: "Number of trades executed today",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/trades-today")),
  },
  {
    id: "next-event",
    name: "Next Event",
    description: "Upcoming economic or earnings event",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/next-event")),
  },
  {
    id: "profit-factor",
    name: "Profit Factor",
    description: "Ratio of gross profit to gross loss",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/profit-factor")),
  },
  {
    id: "day-win-rate",
    name: "Day Win Rate",
    description: "Percentage of profitable trading days",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/day-win-rate")),
  },
  {
    id: "expectancy",
    name: "Expectancy",
    description: "Expected value per trade",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/expectancy")),
  },
  {
    id: "current-streak",
    name: "Current Streak",
    description: "Current consecutive win or loss streak",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/current-streak")),
  },
  {
    id: "largest-win",
    name: "Largest Win",
    description: "Biggest single winning trade",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/largest-win")),
  },
  {
    id: "largest-loss",
    name: "Largest Loss",
    description: "Biggest single losing trade",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/largest-loss")),
  },
  {
    id: "avg-winner",
    name: "Avg Winner",
    description: "Average profit on winning trades",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/avg-winner")),
  },
  {
    id: "avg-loser",
    name: "Avg Loser",
    description: "Average loss on losing trades",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/avg-loser")),
  },
  {
    id: "total-trades",
    name: "Total Trades",
    description: "Total number of closed trades",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/total-trades")),
  },
  {
    id: "max-drawdown",
    name: "Max Drawdown",
    description: "Largest peak-to-trough decline in equity",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/max-drawdown")),
  },
  {
    id: "open-positions",
    name: "Open Positions",
    description: "Number of currently open positions",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/open-positions")),
  },
  {
    id: "best-day",
    name: "Best Day",
    description: "Highest single-day P&L",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/best-day")),
  },
  {
    id: "worst-day",
    name: "Worst Day",
    description: "Lowest single-day P&L",
    category: "stats",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/stats/worst-day")),
  },

  // ── Panel widgets (4 cols, 2 rows, ~320px) ─────────────────────────
  {
    id: "cumulative-pnl",
    name: "Cumulative P&L",
    description: "Running total P&L over time",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/cumulative-pnl")),
  },
  {
    id: "daily-pnl-bars",
    name: "Daily P&L Bars",
    description: "Bar chart of daily profit and loss",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/daily-pnl-bars")),
  },
  {
    id: "drawdown-chart",
    name: "Drawdown Chart",
    description: "Drawdown over time from peak equity",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/drawdown-chart")),
  },
  {
    id: "pnl-by-weekday",
    name: "P&L by Weekday",
    description: "Aggregate P&L broken down by day of week",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/pnl-by-weekday")),
  },
  {
    id: "pnl-by-hour",
    name: "P&L by Hour",
    description: "Aggregate P&L broken down by hour of day",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/pnl-by-hour")),
  },
  {
    id: "win-loss-distribution",
    name: "Win/Loss Distribution",
    description: "Histogram of trade P&L distribution",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/win-loss-distribution")),
  },
  {
    id: "pnl-by-asset-class",
    name: "P&L by Asset Class",
    description: "P&L breakdown by asset class",
    category: "charts",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/charts/pnl-by-asset-class")),
  },

  // ── Board widget (6 cols, 3 rows, ~500px+) ─────────────────────────
  {
    id: "performance-calendar",
    name: "Performance Calendar",
    description: "Monthly calendar with daily P&L, trade count, and win rate",
    category: "charts",
    defaultColSpan: 6,
    defaultRowSpan: 3,
    component: dynamic(() => import("@/components/widgets/charts/performance-calendar")),
  },

  // ── Composite Panel widgets (4 cols, 2 rows) ──────────────────────
  {
    id: "recent-trades",
    name: "Recent Trades",
    description: "Latest closed trades with P&L",
    category: "composite",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/composite/recent-trades")),
  },
  {
    id: "news-feed",
    name: "News Feed",
    description: "Latest market news headlines",
    category: "composite",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/composite/news-feed")),
  },
  {
    id: "tradedesk-score",
    name: "TradeDesk Score",
    description: "Composite trading performance score",
    category: "composite",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/composite/tradedesk-score")),
  },
  {
    id: "performance-summary",
    name: "Performance Summary",
    description: "Key performance metrics at a glance",
    category: "composite",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/composite/performance-summary")),
  },
  {
    id: "top-symbols",
    name: "Top Symbols",
    description: "Best and worst performing symbols",
    category: "composite",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/composite/top-symbols")),
  },

  // ── Market Panel widgets (4 cols, 2 rows) ─────────────────────────
  {
    id: "market-overview",
    name: "Market Overview",
    description: "Major index and asset prices",
    category: "market",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/market/market-overview")),
  },
  {
    id: "economic-calendar",
    name: "Economic Calendar",
    description: "Upcoming economic events and releases",
    category: "market",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/market/economic-calendar")),
  },
  {
    id: "spy-chart",
    name: "SPY Chart",
    description: "S&P 500 ETF price chart",
    category: "market",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    component: dynamic(() => import("@/components/widgets/market/spy-chart")),
  },
  {
    id: "ticker-bar",
    name: "Ticker Bar",
    description: "Scrolling ticker with live prices",
    category: "market",
    defaultColSpan: 12,
    defaultRowSpan: 1,
    component: dynamic(() => import("@/components/widgets/market/ticker-bar")),
  },
];

const widgetMap = new Map<string, WidgetDefinition>(
  widgets.map((w) => [w.id, w])
);

export function getWidget(id: string): WidgetDefinition | undefined {
  return widgetMap.get(id);
}

export function getWidgetsByCategory(): Record<WidgetCategory, WidgetDefinition[]> {
  const result: Record<WidgetCategory, WidgetDefinition[]> = {
    stats: [],
    charts: [],
    composite: [],
    calendar: [],
    market: [],
  };

  for (const widget of widgets) {
    result[widget.category].push(widget);
  }

  return result;
}
